### ISSUE TITLE
Will version 10.1 be supported?

### ISSUE THREAD

**Issue by oahzuw** [wowmodelviewer/wowmodelviewer#5]
Will version 10.1 be supported?

**Comment by natnat201193** [comment]
It already was until recently when the patch 10.1.7 broke it again

**Comment by MisterChaneb** [comment]
> It already was until recently when the patch 10.1.7 broke it again

Will you update against this version or nah?

**Comment by oahzuw** [comment]
> It already was until recently when the patch 10.1.7 broke it again

already  update 10.1.7.x，Will it be supported in the future?
